import 'dart:async';
import 'dart:convert';

import 'package:bloc/bloc.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:meta/meta.dart';

import '../Data/Model/DataModel.dart';
import '../Data/Model/AutoGenaratedModel.dart';
import '../Data/Model/api.dart';
import '../Data/Repo/Dio.dart';



part 'api_call_event.dart';
part 'api_call_state.dart';

class ApiCallBloc extends Bloc<ApiCallEvent, ApiCallState> {
int DrawerStattus=0;
  ApiTest? apiTest;
Autogenerated?autogenerated;
DataModel? dataModel;
 List<int>v=[];
  ApiCallBloc() : super(ApiCallInitial()) {
    on<ApiCallEvent>((event, emit) async{
     if(event is fetchData){
       emit( ApiLoadingData());
       try{
           await  DioHelper.getData(url: 'rest.category/categories').then((value) {
           apiTest= ApiTest.fromJson(jsonDecode(value.data)) ;
           print(value.data);
         });

           await DioHelper.postData(url: 'rest.matgar/getMatgarType', data: {
             "uid":4
           }).then((value) {
             dataModel=DataModel.fromJson(jsonDecode(value.data));
             autogenerated=Autogenerated.fromJson(jsonDecode(value.data));
             print(dataModel!.description);
             print(autogenerated!.categoriesData![4].id);

             print(v);
           });
         emit( ApiLoadedData(apiTest!,dataModel!,autogenerated!));
       }
       catch(e){
         emit( ApiError(e.toString()));
         print(e.toString());
       }


     }
     if(event is openDrawer){
         emit(OpenState(apiTest!));
       }else if(event is closeDrawer){
       emit(ApiLoadedData(apiTest!,dataModel!,autogenerated!));
     }
     if(event is PostEvent){
       await DioHelper.postData(
           url: 'rest.matgar/saveMatgarType', data: {
         "uid":event.uid,
         "description":event.description,
         "ints":event.ints
       }).then((value) {
         emit(PostSucess());
         print(value.data);
         emit(ApiLoadedData(apiTest!,dataModel!,autogenerated!));
       }).catchError((onError) {
         emit(PostError(onError));
         print(onError.toString());
         emit(ApiLoadedData(apiTest!,dataModel!,autogenerated!));

       });

     }
    });

  }

}
